const EXERCISES = {
  'ex-arp': {
    name: "Assisted Ring Pull-Up",
    exType: "strength",
    sets: "3",
    reps: "6",
    ring: true,
    coaching: "Feet supported or band-assisted. Go all the way up \u2014 chin above rings every rep. Control the negative 3\u20134 seconds down. Pull with your back, not your arms.",
    why: "Every rep here builds toward the \u003cstrong\u003epull phase of your muscle-up\u003c/strong\u003e. Lat + scapula strength under ring instability.",
    search: "assisted ring pull up tutorial calisthenics",
    progressRule: "Stop 1\u20132 reps before failure every set. Ready to progress when 3\u00d76 feels like 2 clear reps in reserve for 2 sessions in a row. Gate: every rep fully controlled, chin above rings.",
    intensities: [{"l": "Easier", "d": "Both feet on box \u2014 more leg assistance"}, {"l": "Current", "d": "Band-assisted, 1 foot touch-down allowed"}, {"l": "Harder", "d": "Thinner band, slower negative (5 sec)"}, {"l": "Hardest", "d": "Unassisted pull-up, full range"}],
  },
  'ex-pun': {
    name: "Pull-Up Negative",
    exType: "strength",
    sets: "3",
    reps: "6",
    ring: false,
    coaching: "Jump to top position (chin above bar). Lower yourself as slowly as possible \u2014 aim for 4\u20136 seconds down. This eccentric load builds pull-up strength faster than assisted reps alone.",
    why: "Eccentric strength carries you through the \u003cstrong\u003emuscle-up transition\u003c/strong\u003e where most people fail.",
    search: "pull up negative eccentric tutorial",
    progressRule: "Count every second of the lowering phase. Progress when you control a 6-second negative for all reps across 2 sessions. If the last rep is faster than 4s, you haven't earned the next level yet.",
    intensities: [{"l": "Easier", "d": "2\u20133 second lower, box for jump"}, {"l": "Current", "d": "4\u20136 second negative, 6 reps"}, {"l": "Harder", "d": "8-second lower, pause halfway"}, {"l": "Hardest", "d": "10s lower, L-sit position at top"}],
  },
  'ex-pbdip': {
    name: "Parallel Bar Dips",
    exType: "strength",
    sets: "3",
    reps: "6",
    ring: false,
    coaching: "Slight forward lean for chest emphasis. Elbows track back, not flared. Lower to 90\u00b0. Press up. Don't lock out aggressively at the top.",
    why: "Chest + triceps foundation for \u003cstrong\u003ering dips\u003c/strong\u003e. Build here before progressing to rings.",
    search: "parallel bar dips form tutorial",
    progressRule: "Never to failure \u2014 stop when you have 2 reps left. Progress when 3\u00d76 feels like 3 reps in reserve consistently. Gate: full depth (arms at 90\u00b0) on every single rep.",
    intensities: [{"l": "Easier", "d": "Feet on box for partial support"}, {"l": "Current", "d": "Full bodyweight dip, 6 reps"}, {"l": "Harder", "d": "Slow negative (4 sec), 8 reps"}, {"l": "Hardest", "d": "Ring dips, assisted"}],
  },
  'ex-scdip': {
    name: "Scapula Dips",
    exType: "rehab",
    sets: "3",
    reps: "8",
    ring: false,
    coaching: "Arms locked straight throughout. Lower and raise your body using shoulder blade movement only \u2014 no elbow bend. Small movement, huge long-term impact on shoulder health.",
    why: "Serratus anterior + shoulder health. \u003cstrong\u003eCritical for ring work\u003c/strong\u003e and preventing shoulder injury long-term.",
    search: "scapula dips tutorial shoulder health",
    progressRule: "Quality exercise only \u2014 never to failure. 8 controlled reps with full range every time. Progress intensity when form is perfect for 2 full weeks, not before.",
    intensities: [{"l": "Easier", "d": "Feet on floor, partial bodyweight"}, {"l": "Current", "d": "Full bodyweight, 8 focused reps"}, {"l": "Harder", "d": "Add 2-second hold at bottom"}, {"l": "Hardest", "d": "On rings for extra instability"}],
  },
  'ex-pike': {
    name: "Pike Push-Up",
    exType: "strength",
    sets: "3",
    reps: "8",
    ring: false,
    coaching: "Hips high in an inverted V. Head pushes through at the bottom \u2014 feel your shoulders loading. Your Caliverse routine has dips but no horizontal push \u2014 this fills that gap.",
    why: "Directly builds toward \u003cstrong\u003ehandstand push-ups\u003c/strong\u003e. Also balances shoulder strength to prevent impingement from dip volume.",
    search: "pike push up HSPU progression tutorial",
    progressRule: "Stop 2 reps before failure. Never go to muscular failure on shoulder pressing \u2014 joint stress spikes sharply. Progress when 3\u00d710 with 2 reps in reserve is consistent for 2 weeks.",
    intensities: [{"l": "Easier", "d": "Feet on floor, normal pike"}, {"l": "Current", "d": "Feet slightly elevated, 8 reps"}, {"l": "Harder", "d": "Feet elevated higher, slower eccentric"}, {"l": "Hardest", "d": "Decline pike or wall HSPU lowering"}],
  },
  'ex-sldl': {
    name: "Single Leg Deadlift (Assisted)",
    exType: "strength",
    sets: "3",
    reps: "8",
    ring: true,
    coaching: "Hold a ring for balance. Hinge at the hip \u2014 back stays flat and long. Feel the hamstring of the standing leg load. This is about the hip hinge pattern, not balance challenge.",
    why: "Hamstring + glute strength. Both directly \u003cstrong\u003eprotect your knee and decompress your lower back\u003c/strong\u003e. One of the most important movements in this program.",
    search: "single leg deadlift assisted form tutorial",
    progressRule: "Progress when you can do 3\u00d78/side using just a fingertip touch on the support. Gate: back must stay completely flat throughout every rep. Any rounding = stay at current level.",
    intensities: [{"l": "Easier", "d": "Heavier assistance, smaller range"}, {"l": "Current", "d": "Ring hold, 8 reps each side"}, {"l": "Harder", "d": "Lighter touch on support, deeper hinge"}, {"l": "Hardest", "d": "Unassisted, slow 3-second lowering"}],
  },
  'ex-wst': {
    name: "Wall Sit",
    exType: "hold",
    sets: "3",
    reps: "45s",
    ring: false,
    coaching: "Back flat on wall. Thighs parallel to floor. Knees track over toes \u2014 no caving in. Should burn in the quads, especially the inner quad (VMO). Add 5 seconds per week.",
    why: "VMO + quad endurance under sustained isometric load. \u003cstrong\u003eKnee joint protection\u003c/strong\u003e with zero impact.",
    search: "wall sit proper form VMO benefits",
    progressRule: "Add 5 seconds per week once you complete the full hold 3 sessions in a row with form intact. Gate: knees must track over toes the entire hold. Any caving = restart that week.",
    intensities: [{"l": "Easier", "d": "Higher angle, 30 seconds"}, {"l": "Current", "d": "Parallel thighs, 45 seconds"}, {"l": "Harder", "d": "60 seconds, eyes closed"}, {"l": "Hardest", "d": "Single leg wall sit, supported"}],
  },
  'ex-slgb': {
    name: "Single-Leg Glute Bridge",
    exType: "strength",
    sets: "3",
    reps: "12",
    ring: false,
    coaching: "Lie on back, one knee bent foot flat, other leg extended. Drive through heel. Squeeze the glute at the top for 1\u20132 seconds. If you feel it in your hamstring or lower back, reposition your foot closer to your hips.",
    why: "Posterior chain activation. \u003cstrong\u003eGlute strength protects both your back and knee simultaneously\u003c/strong\u003e \u2014 the most efficient injury-prevention exercise you have.",
    search: "single leg glute bridge tutorial form",
    progressRule: "Progress when 3\u00d712/side with a 2-second glute squeeze feels like 4+ reps left. Should feel this in the glute \u2014 not the hamstring or lower back.",
    intensities: [{"l": "Easier", "d": "Both feet on floor, standard bridge"}, {"l": "Current", "d": "Single leg, 12 reps with squeeze"}, {"l": "Harder", "d": "Foot elevated on box, 10 reps"}, {"l": "Hardest", "d": "Foot elevated + 3-second hold at top"}],
  },
  'ex-rsap': {
    name: "Ring Straight Arm Plank",
    exType: "hold",
    sets: "3",
    reps: "40s",
    ring: true,
    coaching: "Rings at low height, arms straight, body in plank. Ring instability multiplies core demand enormously vs floor plank. Ribs down, hips neutral. If lower back sags, raise rings slightly.",
    why: "Anti-extension core on unstable surface. Directly builds the \u003cstrong\u003ehollow body position\u003c/strong\u003e needed for every skill and for daily back protection.",
    search: "ring straight arm plank core tutorial",
    progressRule: "Add 5 seconds per week. Gate: hips must not drop at any point. One hip drop = set ends. Quality of position beats hold time.",
    intensities: [{"l": "Easier", "d": "Rings higher, 25 seconds"}, {"l": "Current", "d": "Rings at calf height, 40 seconds"}, {"l": "Harder", "d": "Rings lower, 50 seconds"}, {"l": "Hardest", "d": "Add ring push-out at end of hold"}],
  },
  'ex-hkr': {
    name: "Hanging Knee Raise",
    exType: "strength",
    sets: "3",
    reps: "8",
    ring: false,
    coaching: "From dead hang. Pull knees to chest using abs \u2014 not momentum. Lower slowly. If you start swinging, stop and restart from still. Lower back is safe here because the spine is decompressed in the hang.",
    why: "Hip flexor + lower ab strength. \u003cstrong\u003eLower back safe\u003c/strong\u003e because of the hanging/decompressed position. Progress to leg raises over time.",
    search: "hanging knee raise no swing tutorial",
    progressRule: "Progress when 3\u00d710 has zero swing and a controlled 3-second lowering on every rep. Any momentum use = restart that set. Form is the entire point.",
    intensities: [{"l": "Easier", "d": "Bent knees to 90\u00b0, small range"}, {"l": "Current", "d": "Knees to chest, 8 controlled reps"}, {"l": "Harder", "d": "Slower lowering, 10\u201312 reps"}, {"l": "Hardest", "d": "Straight leg raises (L-sit path)"}],
  },
  'ex-rar': {
    name: "Ring Australian Row",
    exType: "strength",
    sets: "3",
    reps: "8",
    ring: true,
    coaching: "Body at 45\u00b0 to floor, rings to chest, elbows back and tight. The lower your body angle, the harder it is. Progress by lowering your body angle weekly. Pull with your back \u2014 initiate with shoulder blades, not arms.",
    why: "Mid-back + rhomboids. Horizontal pulling \u003cstrong\u003edirectly improves the forward posture that compresses your lower back\u003c/strong\u003e.",
    search: "ring australian row tutorial progression",
    progressRule: "Lower your body angle when 3\u00d710 at current angle has 3 reps clearly in reserve. Gate: elbow must pass fully past torso every rep. Partial range doesn't count.",
    intensities: [{"l": "Easier", "d": "Body more upright, 45\u00b0 angle"}, {"l": "Current", "d": "45\u00b0 body, 8 reps"}, {"l": "Harder", "d": "Body more horizontal, 10 reps"}, {"l": "Hardest", "d": "Nearly horizontal, slow eccentric"}],
  },
  'ex-pbsh': {
    name: "Parallel Bar Support Hold",
    exType: "hold",
    sets: "3",
    reps: "30s",
    ring: true,
    coaching: "Arms locked, shoulders depressed (pushed down away from ears), body straight. This is the top position of dips and muscle-up. Progress to ring support hold when 30s is consistent.",
    why: "Support position strength. The \u003cstrong\u003emuscle-up requires you to hold this position\u003c/strong\u003e at the top \u2014 without it, you fall forward.",
    search: "parallel bar support hold scapula depression",
    progressRule: "Progress to rings when you can hold 30s for all 3 sets with shoulders actively depressed (not shrugged up). Hold quality matters more than time.",
    intensities: [{"l": "Easier", "d": "Feet lightly on box, 20 seconds"}, {"l": "Current", "d": "Full support hold, 30 seconds"}, {"l": "Harder", "d": "45 seconds, active shoulder depression"}, {"l": "Hardest", "d": "Ring support hold, 20 seconds"}],
  },
  'ex-hb': {
    name: "Hollow Body Hold",
    exType: "rehab",
    sets: "3",
    reps: "25s",
    ring: false,
    coaching: "Lower back FLAT on floor \u2014 this is the whole exercise. Arms overhead, legs extended low. Ribs pressed down. If lower back lifts, raise your legs higher. Progress by lowering legs each week.",
    why: "The foundation of \u003cstrong\u003eevery calisthenics skill AND the best lower back protection\u003c/strong\u003e exercise that exists. Both at the same time.",
    search: "hollow body hold tutorial progression calisthenics",
    progressRule: "Lower back must stay completely flat for the FULL hold \u2014 even the last 5 seconds. Only add 5s when the flat-back standard is met. Never fight through back lifting.",
    intensities: [{"l": "Easier", "d": "Knees bent, arms by sides, 15 seconds"}, {"l": "Current", "d": "Arms overhead, legs low, 25 seconds"}, {"l": "Harder", "d": "35 seconds, legs lower"}, {"l": "Hardest", "d": "Add arm circles, legs fully extended"}],
  },
  'ex-db': {
    name: "Dead Bug",
    exType: "rehab",
    sets: "3",
    reps: "8",
    ring: false,
    coaching: "Lower back pressed INTO floor throughout \u2014 non-negotiable. Arms up, knees at 90\u00b0. Extend opposite arm and leg slowly (3\u20134 seconds). Return. If your lower back lifts, reduce range of motion first.",
    why: "Anti-extension core stability. Keeps the lumbar from extending under load \u2014 \u003cstrong\u003ethe exact motion that causes your back flare-ups\u003c/strong\u003e.",
    search: "dead bug exercise lower back rehab tutorial",
    progressRule: "Back stays on the floor 100% of the time \u2014 not 95%. If it lifts even once, reduce the range of motion first before adding extension. This is the whole exercise.",
    intensities: [{"l": "Easier", "d": "One limb at a time, small range"}, {"l": "Current", "d": "Opposite arm/leg, 3-second extend"}, {"l": "Harder", "d": "Add 1-second hold at full extension"}, {"l": "Hardest", "d": "Add resistance band between hands and knees"}],
  },
  'ex-tke': {
    name: "Slow Step-Down (VMO Focus)",
    exType: "rehab",
    sets: "3",
    reps: "10/side",
    ring: false,
    coaching: "Stand on your box. Lower your heel toward the floor in 4 full seconds \u2014 count it out loud. Touch and return without collapsing. Knee tracks directly over your second toe the entire way down. This eccentric load is what reactivates the VMO.",
    why: "Directly retrains VMO activation through eccentric loading \u2014 the \u003cstrong\u003esame stimulus as TKE but with your box instead of a band\u003c/strong\u003e. Standard physio protocol for MCL recovery, no equipment needed beyond your step.",
    search: "slow step down eccentric VMO rehab box",
    progressRule: "4-second lowering is non-negotiable \u2014 if any rep is faster than 3 seconds, stop the set. Progress to a higher box when 3\u00d710/side with perfect knee tracking feels like 4 reps remain. Gate: zero knee caving, zero speed cheating.",
    intensities: [{"l": "Easier", "d": "Lower box or step, 3-second lower"}, {"l": "Current", "d": "Low box, 4-second lower, 10/side"}, {"l": "Harder", "d": "Higher box, 4-second lower"}, {"l": "Hardest", "d": "5-second lower, higher box, pause at bottom"}],
  },
  'ex-wsit': {
    name: "Wall Sit (VMO Focus)",
    exType: "hold",
    sets: "3",
    reps: "20s",
    ring: false,
    coaching: "Thighs parallel. Add 5 seconds per week. At week 6 you should be at 45\u201350 seconds here. This finishes the session with sustained quad loading.",
    why: "VMO endurance finisher. Closes the session with the \u003cstrong\u003emuscle that protects your knee most\u003c/strong\u003e.",
    search: "wall sit benefits quad VMO",
    progressRule: "Add 5 seconds per week. Form gates it: knees level, no forward lean. This is VMO endurance training \u2014 discomfort is the signal, grinding is not the goal.",
    intensities: [{"l": "Easier", "d": "Higher angle, 15 seconds"}, {"l": "Current", "d": "Parallel, 20 seconds"}, {"l": "Harder", "d": "30\u201345 seconds"}, {"l": "Hardest", "d": "Single leg wall sit, 15 seconds assisted"}],
  },
  'ex-fhc': {
    name: "Fire Hydrant Circles",
    exType: "mobility",
    sets: "1",
    reps: "8/side",
    ring: false,
    coaching: "On all fours, lift one knee out to side and make large circles. Full range in both directions. Slow and deliberate. This lubricates the hip joint.",
    why: "Hip capsule warm-up. \u003cstrong\u003eCritical first movement with your MCL history\u003c/strong\u003e \u2014 opens the joint before any load goes through it.",
    search: "fire hydrant circles hip mobility tutorial",
    progressRule: "Mobility is never to pain. Mild end-range discomfort is fine. Any sharp or pinching sensation = back off immediately. Depth increases over weeks, not sessions.",
    intensities: [],
  },
  'ex-cc': {
    name: "Cossack Squat",
    exType: "strength",
    sets: "3",
    reps: "12/side",
    ring: false,
    coaching: "Feet wide. Shift weight to one side \u2014 squat as deep as possible on that leg while the other leg stays straight with foot flat or slightly raised. Open the hip out. This is mobility and strength at the same time. Hold the bottom for 2 seconds.",
    why: "Lateral hip and adductor strength that no other exercise in this program hits. \u003cstrong\u003eHip strength from all angles prevents the compensations that cause knee and back pain.\u003c/strong\u003e",
    search: "cossack squat hip mobility lateral strength",
    progressRule: "Deepen range gradually. Progress intensity when you can reach full depth (thigh parallel or below) with a 2-second pause and no foot pronation on the squatting side.",
    intensities: [{"l": "Easier", "d": "Limited depth, hands on floor for balance"}, {"l": "Current", "d": "Working depth, 2-second hold, 12/side"}, {"l": "Harder", "d": "Full depth, no hands, 12/side"}, {"l": "Hardest", "d": "Assisted heel raise, maximum depth, slow tempo"}],
  },
  'ex-pcp': {
    name: "Prying Cobra to Pike",
    exType: "mobility",
    sets: "1",
    reps: "30s",
    ring: false,
    coaching: "From cobra (chest up, hips down), push back into pike/downward dog. Flow between the two. Hold the pike end position for 3\u20135 breaths.",
    why: "Hip flexor + hamstring combined. \u003cstrong\u003eTight hip flexors are a primary driver of lower back pain\u003c/strong\u003e \u2014 this directly addresses yours.",
    search: "prying cobra to pike hip flexor stretch",
    progressRule: "Extend the pike hold by 1 breath each week \u2014 aim for 5 full breaths eventually. Never force the range. Hip flexors release on their own timeline.",
    intensities: [],
  },
  'ex-cpp': {
    name: "Child Pose Pulses",
    exType: "mobility",
    sets: "1",
    reps: "30s",
    ring: false,
    coaching: "Arms long overhead. Gently pulse further into the stretch. Lower back fully releases. Use this any time your back is tight \u2014 morning, before bed, between sets.",
    why: "Lumbar decompression. \u003cstrong\u003eOne of the best lower back relief tools you have\u003c/strong\u003e \u2014 accessible any time, anywhere.",
    search: "child pose pulses lower back stretch",
    progressRule: "Pure restoration \u2014 no progression target. Use this any time your lower back is tight, regardless of whether it's a training day. The goal is to release, not achieve.",
    intensities: [],
  },
  'ex-tbr': {
    name: "Thoracic Bridge",
    exType: "mobility",
    sets: "1",
    reps: "6/side",
    ring: false,
    coaching: "From a deep lunge, rotate thoracic spine and reach arm overhead. Open the chest. Focus on rotation, not just reaching. Breathe into each rep.",
    why: "Thoracic extension + rotation. \u003cstrong\u003eMid-back mobility opens the path\u003c/strong\u003e for HSPU and ring overhead work.",
    search: "thoracic bridge mobility lunge rotation",
    progressRule: "More time at end-range beats more reps. If rotation is restricted, slow down and breathe into it. Fewer deep reps is always better than many shallow ones.",
    intensities: [],
  },
  'ex-rsrdl': {
    name: "Romanian Split Stance Deadlift",
    exType: "mobility",
    sets: "1",
    reps: "10/side",
    ring: false,
    coaching: "Split stance, hinge at hip, back flat and long. Feel the front leg hamstring load. Return by driving hip forward. Pure hip hinge \u2014 spine stays neutral.",
    why: "Single-leg hamstring + glute loading in a mobility context. \u003cstrong\u003eBridges your mobility work and strength work.\u003c/strong\u003e",
    search: "romanian split stance deadlift mobility",
    progressRule: "Progress to a lighter touch on the support when the hinge feels automatic and smooth. Back must stay flat \u2014 any rounding means you've gone too far into the range.",
    intensities: [],
  },
  'ex-gbale': {
    name: "Glute Bridge w/ Alt. Leg Extension",
    exType: "rehab",
    sets: "2",
    reps: "6/side",
    ring: false,
    coaching: "Bridge up, then extend one leg while holding position. Keep hips level \u2014 don't let them rotate. This challenges hip stability more than a standard bridge.",
    why: "Hip stability + posterior chain wake-up. \u003cstrong\u003eDirectly protects both knee and lumbar simultaneously.\u003c/strong\u003e",
    search: "glute bridge alternating leg extension tutorial",
    progressRule: "Progress when hips stay perfectly level for every rep with no visible wobble. If hips drop or rotate, reduce the range of the leg extension \u2014 don't compensate.",
    intensities: [],
  },
  'ex-spuk': {
    name: "Scapula Push-Up (Kneeling)",
    exType: "rehab",
    sets: "2",
    reps: "8",
    ring: false,
    coaching: "On knees, arms locked. Let shoulder blades come together (sink), then push them apart (protract). Arms stay completely straight. Tiny movement, huge long-term impact.",
    why: "Serratus anterior. \u003cstrong\u003eShoulder blade control is the #1 foundation\u003c/strong\u003e for all ring work, pull-ups, and posture.",
    search: "scapula push up kneeling serratus tutorial",
    progressRule: "Never to failure. Stop if range reduces. 8 full-range reps with clear protraction and retraction is always the standard. Progress to full push-up position when this feels easy.",
    intensities: [],
  },
  'ex-syr': {
    name: "Scapula Y Raise",
    exType: "rehab",
    sets: "2",
    reps: "10",
    ring: false,
    coaching: "Prone or standing. Arms in Y shape overhead. Lift using the lower trapezius \u2014 not upper traps or shoulders. Keep neck long and shoulders away from ears.",
    why: "Lower trapezius. \u003cstrong\u003eThe most undertrained postural muscle.\u003c/strong\u003e These + T raises are the best long-term posture investment in this program.",
    search: "scapula Y raise lower trap tutorial",
    progressRule: "Slower is always better. If upper traps take over (shoulder creeps toward ear), lower the load or pause mid-rep. Progress when form is flawless for 2 full sessions.",
    intensities: [],
  },
  'ex-qle': {
    name: "Quadruped Leg Extension",
    exType: "rehab",
    sets: "2",
    reps: "8/side",
    ring: false,
    coaching: "On all fours, extend one leg straight back. Keep hips perfectly level \u2014 no rotation. This is about glute med activation, not leg height.",
    why: "Glute med + lumbar stabilizers. \u003cstrong\u003eRetrains the exact pattern disrupted by your MCL injury.\u003c/strong\u003e",
    search: "quadruped leg extension glute activation",
    progressRule: "The gate is hip level \u2014 if hips rotate even slightly, the set ends. Add reps only when hip rotation is completely eliminated across multiple sessions.",
    intensities: [],
  },
  'ex-str': {
    name: "Scapula T Raise",
    exType: "rehab",
    sets: "2",
    reps: "10",
    ring: false,
    coaching: "Like Y raise but arms at 90\u00b0 to your body (T shape). Thumbs up. Squeeze shoulder blades together at the top. Slower is better.",
    why: "Mid-trapezius. Pairs with Y raise for complete shoulder health. \u003cstrong\u003eTogether they fix forward shoulder posture permanently\u003c/strong\u003e over time.",
    search: "scapula T raise mid trap posture",
    progressRule: "Same gate as Y raise \u2014 lower traps, not upper. Add a 2-second pause at the top once the movement feels solid. Progress intensity only when these feel genuinely easy for 2 weeks.",
    intensities: [],
  },
  'ex-csq': {
    name: "Cossack Squat",
    exType: "mobility",
    sets: "2",
    reps: "5/side",
    ring: false,
    coaching: "Wide stance. Shift weight to one side, lowering into a side squat. Other leg straight with foot flat or toes up. Go only as deep as comfortable.",
    why: "Hip + adductor mobility in a loaded position. \u003cstrong\u003eProgress depth slowly \u2014 this is months of patient work.\u003c/strong\u003e",
    search: "cossack squat hip mobility tutorial",
    progressRule: "Depth increases over months. Gate for going deeper: can you hold current depth for 5 full breaths without gripping anything? Only then try deeper.",
    intensities: [],
  },
  'ex-trdl': {
    name: "Thoracic Rotation Deep Lunge",
    exType: "mobility",
    sets: "2",
    reps: "10",
    ring: false,
    coaching: "Deep lunge. Rotate thoracic spine and reach arm toward ceiling. Open the chest. Return. This hits your two injury areas simultaneously.",
    why: "\u003cstrong\u003eBest single exercise for hip + thoracic spine combined.\u003c/strong\u003e Keep doing this forever.",
    search: "thoracic rotation deep lunge mobility",
    progressRule: "Focus on rotation depth over rep count. A few reps with full rotation is better than many shallow ones. Breathing into each rep is the technique.",
    intensities: [],
  },
  'ex-fmr': {
    name: "Frog Mobility Rotation",
    exType: "mobility",
    sets: "2",
    reps: "10",
    ring: false,
    coaching: "Wide knees, feet turned out. Rock forward and back while adding rotation. Opens inner groin and hip capsule. Progress depth very slowly.",
    why: "Inner groin + hip capsule. The mobility here \u003cstrong\u003etranslates to better squatting and less knee stress.\u003c/strong\u003e",
    search: "frog mobility rotation hip stretch",
    progressRule: "Any inner-groin pinching = back off immediately. This is months of patient adaptation. Consistent gentle pressure beats aggressive one-time attempts.",
    intensities: [],
  },
  'ex-dh': {
    name: "Dead Hang",
    exType: "hold",
    sets: "2",
    reps: "25s",
    ring: false,
    coaching: "Hang from bar, body relaxed. Let gravity decompress your spine. Shoulders should rise naturally \u2014 don't pull them down. Increase by 5 seconds per week.",
    why: "Spinal decompression + shoulder opening. \u003cstrong\u003eThe most underrated lower back treatment\u003c/strong\u003e you have access to for free.",
    search: "dead hang spinal decompression shoulder mobility",
    progressRule: "Add 5 seconds per week. Goal is a 60-second hang by end of Phase 1. Shoulders should naturally rise toward ears \u2014 don't pull them down. Let gravity do the decompression work.",
    intensities: [{"l": "Easier", "d": "20 seconds, drop if grip fails"}, {"l": "Current", "d": "25 seconds, body relaxed"}, {"l": "Harder", "d": "35 seconds"}, {"l": "Hardest", "d": "45\u201360 seconds"}],
  },
  'ex-str2': {
    name: "Supine Thoracic Rotation",
    exType: "mobility",
    sets: "2",
    reps: "10/side",
    ring: false,
    coaching: "Lie on side, knees bent at 90\u00b0, hands stacked out front. Rotate top arm across to the other side, following with eyes. Let gravity open the chest to ceiling.",
    why: "Gentle thoracic mobility. \u003cstrong\u003eGreat for morning stiffness or post-strength soreness.\u003c/strong\u003e Does not stress lower back at all.",
    search: "supine thoracic rotation tutorial",
    progressRule: "Let gravity open the chest \u2014 no forcing. The rotation should increase naturally over weeks. Breathing into the stretch is the primary technique here.",
    intensities: [],
  },
  'ex-tke2': {
    name: "Slow Step-Down (VMO Focus)",
    exType: "rehab",
    sets: "2",
    reps: "10/side",
    ring: false,
    coaching: "Stand on your box, one foot hanging. Lower the hanging heel toward the floor in 4 slow seconds. Touch, return. Knee tracks over your toes \u2014 no inward collapse allowed. Feel the inner quad fire on the way down.",
    why: "VMO eccentric isolation. \u003cstrong\u003eStandard MCL physio protocol\u003c/strong\u003e \u2014 the 4-second lowering is what forces the VMO to engage rather than the quads compensating around it.",
    search: "slow step down eccentric VMO box rehab",
    progressRule: "Never rush the lowering. If you feel hamstring or outer quad taking over, check your knee tracking and slow down. 2 sets here is maintenance \u2014 Monday's 3 sets is the primary dose.",
    intensities: [{"l": "Easier", "d": "Lower box, 3-second lower, hand on wall"}, {"l": "Current", "d": "Box step, 4-second lower, 10/side"}, {"l": "Harder", "d": "Higher box, 4-second lower"}, {"l": "Hardest", "d": "5-second lower, pause at bottom"}],
  },
  'ex-lbw': {
    name: "Side-Lying Hip Abduction",
    exType: "rehab",
    sets: "2",
    reps: "15/side",
    ring: false,
    coaching: "Lie on your side, body straight, bottom arm under head. Lift the top leg to about 45\u00b0 \u2014 toes pointing slightly down, not up. Pause 1 second at the top. Lower slowly. Feel the outer hip burning, not your lower back. If your back arches, reduce the range.",
    why: "Glute medius activation \u2014 \u003cstrong\u003esame muscle as lateral band walks, zero equipment needed\u003c/strong\u003e. Stabilizes the pelvis over the knee. Weakness here is one of the most common causes of MCL re-injury.",
    search: "side lying hip abduction glute medius bodyweight",
    progressRule: "Outer hip burning is the signal \u2014 if you feel lower back instead, reduce the leg height. Progress to a dumbbell held on the thigh when 3\u00d715 with a 1-second pause feels easy across 2 sessions.",
    intensities: [{"l": "Easier", "d": "Smaller range, no pause"}, {"l": "Current", "d": "45\u00b0 lift, 1s pause, 15/side"}, {"l": "Harder", "d": "2-second pause at top"}, {"l": "Hardest", "d": "Light dumbbell on thigh, 12/side"}],
  },
  'ex-slbal': {
    name: "Single-Leg Balance Hold",
    exType: "rehab",
    sets: "2",
    reps: "30s/side",
    ring: false,
    coaching: "Slight knee bend. Start with eyes open. Progress to eyes closed when that feels solid. Eyes closed forces the proprioceptive system to work extremely hard.",
    why: "Proprioceptive retraining. \u003cstrong\u003eThe MCL is rich in nerve endings\u003c/strong\u003e that tell your brain where your knee is. Injury disrupts this \u2014 balance work restores it.",
    search: "single leg balance proprioception MCL rehab eyes closed",
    progressRule: "Progress to eyes closed only when 30 seconds eyes-open feels completely stable. Wobbling is fine and normal \u2014 falling off = back to eyes open. This takes weeks.",
    intensities: [{"l": "Easier", "d": "Eyes open, 20 seconds, hand on wall"}, {"l": "Current", "d": "Eyes open, 30 seconds"}, {"l": "Harder", "d": "Eyes closed, 20 seconds"}, {"l": "Hardest", "d": "Eyes closed, 30\u201345 seconds"}],
  },
  'ex-9090': {
    name: "90-90 Hip Stretch",
    exType: "mobility",
    sets: "2",
    reps: "45s/side",
    ring: false,
    coaching: "Both knees at 90\u00b0, one in front, one to the side. Tall spine. Lean gently into the front hip. Feel the hip flexor and external rotator stretch.",
    why: "Hip flexor + external rotation. \u003cstrong\u003eTight hips directly contribute to lower back and knee stress.\u003c/strong\u003e",
    search: "90 90 hip stretch tutorial hip flexor",
    progressRule: "Progress to 60 seconds when 45 seconds feels genuinely comfortable for 2+ sessions. Never force the hip toward the floor \u2014 let gravity pull it down gradually.",
    intensities: [{"l": "Easier", "d": "Supported on hands, 30 seconds"}, {"l": "Current", "d": "Tall spine, 45 seconds"}, {"l": "Harder", "d": "Fold forward, 60 seconds"}, {"l": "Hardest", "d": "Fold forward + reach, 60+ seconds"}],
  },
  'ex-sup': {
    name: "Superman Hold",
    exType: "hold",
    sets: "3",
    reps: "10s",
    ring: false,
    coaching: "Prone, arms extended overhead. Lift chest and legs simultaneously. Hold. Feel the entire posterior chain \u2014 erectors, glutes, hamstrings working together.",
    why: "Erector spinae + glute endurance. \u003cstrong\u003ePairs with hollow body to brace the spine from both sides.\u003c/strong\u003e",
    search: "superman hold back extension posterior chain",
    progressRule: "Add 2\u20133 seconds per week. Key signal: if lower back cramps before glutes and hamstrings fatigue, reduce the hold time. This should be felt in the posterior chain, not the spine.",
    intensities: [{"l": "Easier", "d": "Arms by sides, 8 seconds"}, {"l": "Current", "d": "Arms overhead, 10 seconds"}, {"l": "Harder", "d": "15 seconds"}, {"l": "Hardest", "d": "20 seconds with flutter kick"}],
  },
  'ex-dcs': {
    name: "Doorway Chest Stretch",
    exType: "mobility",
    sets: "1",
    reps: "45s/side",
    ring: false,
    coaching: "Arm at 90\u00b0 in doorframe, lean body through. Try two positions \u2014 arm at 90\u00b0 and arm at 45\u00b0. Different angles hit different parts of the pec.",
    why: "Pec minor release. \u003cstrong\u003eEssential for ring dips and shoulder health.\u003c/strong\u003e Tight pecs pull shoulders forward and compress the thoracic spine.",
    search: "doorway chest stretch pec minor release",
    progressRule: "Progress by leaning slightly further through the doorway each week. If you feel any front-of-shoulder pinching, adjust arm angle. Do both 90\u00b0 and 45\u00b0 versions.",
    intensities: [],
  },
  'ex-pig': {
    name: "Pigeon Pose (modified)",
    exType: "mobility",
    sets: "1",
    reps: "45s/side",
    ring: false,
    coaching: "Front knee at 90\u00b0, support on hands or forearms. Sink into the hip. Breathe. Don't force depth \u2014 let gravity do the work over time.",
    why: "Deep hip flexor + glute stretch. The mobility here \u003cstrong\u003edirectly shows up as pain-free movement in your daily life.\u003c/strong\u003e",
    search: "pigeon pose modified hip flexor stretch tutorial",
    progressRule: "Progress from hands to forearms to forehead on floor \u2014 over months. Never force the hip down. The release happens in the exhale. Breathe into the hip.",
    intensities: [],
  },
  'ex-bss': {
    name: "Bulgarian Split Squat",
    exType: "strength",
    sets: "3",
    reps: "8/side",
    ring: true,
    coaching: "Rear foot elevated on box. Hold rings lightly for balance only \u2014 do not pull on them. Front shin stays vertical. Lower until rear knee approaches floor. Drive through front heel to stand. This is the hardest exercise in the program \u2014 treat it with respect.",
    why: "The single best bodyweight leg strength movement. \u003cstrong\u003eDirectly builds the quad, glute, and hamstring strength\u003c/strong\u003e that protects your knee and lower back simultaneously. Unilateral training fixes imbalances that bilateral work hides.",
    search: "bulgarian split squat rings tutorial progression",
    progressRule: "Start conservative \u2014 8/side feels easy at first but accumulates. Progress when 3\u00d78/side with 3 reps in reserve and perfect shin angle is consistent for 2 sessions. Gate: front knee must track over toes throughout, zero trunk collapse.",
    intensities: [{"l": "Easier", "d": "Lower box, hands on rings, smaller range"}, {"l": "Current", "d": "Box at knee height, rings for balance, 8/side"}, {"l": "Harder", "d": "Pause 2s at bottom, 10/side"}, {"l": "Hardest", "d": "No ring support, arms crossed, 10/side"}],
  },
  'ex-noc': {
    name: "Nordic Curl (Ring-Assisted)",
    exType: "strength",
    sets: "3",
    reps: "5",
    ring: true,
    coaching: "Anchor rings at low height, loop under ankles or hold behind. Kneel on mat, rings behind your ankles. Lower your body forward as slowly as possible \u2014 5 full seconds. Catch yourself at the bottom. Pull up with the rings to return. The eccentric phase (lowering) is the entire training stimulus.",
    why: "The most powerful hamstring strengthening exercise that exists. \u003cstrong\u003eReduces hamstring injury risk by over 50% in studies.\u003c/strong\u003e Also directly protects the knee by building the posterior chain that stabilizes it.",
    search: "nordic curl ring assisted eccentric hamstring",
    progressRule: "5-second lowering is the gate \u2014 no exceptions. Progress from 3 to 5 to 8 seconds before adding reps. Use more ring assistance to return until you're strong enough to pull up unassisted. This builds over months, not weeks.",
    intensities: [{"l": "Easier", "d": "6+ seconds lower, full ring assist up"}, {"l": "Current", "d": "5-second lower, ring assist to return, 5 reps"}, {"l": "Harder", "d": "7-second lower, minimal ring assist"}, {"l": "Hardest", "d": "Full Nordic \u2014 lower and raise unassisted"}],
  },
  'ex-psq': {
    name: "Pistol Squat Progression",
    exType: "skill",
    sets: "3",
    reps: "5/side",
    ring: true,
    coaching: "Hold one ring. Extend one leg forward. Sit back and down on the standing leg \u2014 as deep as you can go. Drive through the heel to stand. The ring is only for balance \u2014 do not use it for strength. Each week, use less ring tension.",
    why: "Single-leg quad and glute strength at full range. \u003cstrong\u003eThe most complete lower body test you can do with bodyweight.\u003c/strong\u003e Balance, strength, and mobility simultaneously.",
    search: "pistol squat progression beginner ring assisted",
    progressRule: "Reduce ring tension progressively over weeks. Progress level when you can touch the bottom position with only a fingertip on the ring for all reps.",
    intensities: [{"l": "Easier", "d": "Squat to box with ring, limited depth"}, {"l": "Current", "d": "Full depth with ring support, 5/side"}, {"l": "Harder", "d": "Minimal ring contact, full depth"}, {"l": "Hardest", "d": "Unassisted pistol squat, 5/side"}],
  },
  'ex-ht': {
    name: "Hip Thrust (Box)",
    exType: "strength",
    sets: "3",
    reps: "12",
    ring: false,
    coaching: "Upper back on box edge, feet flat. Drive hips up by squeezing glutes \u2014 not by arching lower back. Pause 1 full second at the top with glutes actively contracted. This pause is non-negotiable. Progress: slow the descent to 3 seconds.",
    why: "Peak glute activation. \u003cstrong\u003eStronger glutes directly reduce lower back loading\u003c/strong\u003e \u2014 they are the primary hip extensor the back compensates for when weak.",
    search: "hip thrust box bodyweight glute tutorial",
    progressRule: "Add the 3-second eccentric when 3\u00d712 with 2-second holds feels like 4 reps remain. Gate: glute must be the primary driver \u2014 if you feel lower back, reposition feet closer to hips.",
    intensities: [{"l": "Easier", "d": "Both feet, no pause, 10 reps"}, {"l": "Current", "d": "Both feet, 1-second pause, 12 reps"}, {"l": "Harder", "d": "3-second eccentric + 1-second pause"}, {"l": "Hardest", "d": "Single-leg hip thrust, 8/side"}],
  },
  'ex-sldl2': {
    name: "Single-Leg Romanian Deadlift",
    exType: "strength",
    sets: "3",
    reps: "8/side",
    ring: true,
    coaching: "Hold one ring lightly. Hinge at the hip \u2014 back stays long and flat, neutral spine throughout. Feel the hamstring of the standing leg loading as the torso descends. This is a hip hinge, not a squat. Toe of the floating leg stays level with the hip, not swinging for momentum.",
    why: "Hamstring + glute eccentrically loaded through full range. \u003cstrong\u003eThe hip hinge pattern is the most protective movement for your lower back\u003c/strong\u003e \u2014 and the most undertrained.",
    search: "single leg RDL hip hinge progression tutorial",
    progressRule: "Progress from ring hold \u2192 fingertip touch \u2192 no contact. Gate: back must remain completely flat. Any spinal rounding means the load is too high \u2014 reduce range before reducing reps.",
    intensities: [{"l": "Easier", "d": "Both hands on ring, limited range"}, {"l": "Current", "d": "One ring, full range, 8/side"}, {"l": "Harder", "d": "Fingertip touch only, slower descent"}, {"l": "Hardest", "d": "Unassisted, 4-second eccentric, 8/side"}],
  },
  'ex-rrow2': {
    name: "Ring Row",
    exType: "conditioning",
    sets: "3",
    reps: "10",
    ring: true,
    coaching: "Body as horizontal as possible. Rings to chest, elbows back. Maintain hollow body throughout. The more horizontal, the harder.",
    why: "Mid/upper back in a cardio context. Posture muscles need endurance, not just isolated strength.",
    search: "ring row tutorial progression horizontal",
    progressRule: "Lower body angle when 15+ reps are easy across all 3 rounds. Stop a set if hollow body collapses.",
    intensities: [{"l": "Easier", "d": "Body more upright, 45\u00b0"}, {"l": "Current", "d": "45\u00b0, 10 reps"}, {"l": "Harder", "d": "More horizontal, 10 reps"}, {"l": "Hardest", "d": "Near-horizontal, pause at top"}],
  },
  'ex-sqjump': {
    name: "Squat Hold to Jump",
    exType: "conditioning",
    sets: "3",
    reps: "10",
    ring: false,
    coaching: "Drop into a squat, hold 2 seconds, then drive up explosively. Land softly \u2014 absorb through hips and knees, not just the knees. Low impact option: remove the jump and just drive up onto toes.",
    why: "Lower body power + cardio. Trains the fast-twitch fibers the slow strength work doesn't reach. \u003cstrong\u003ePower is what converts strength into athletic movement.\u003c/strong\u003e",
    search: "squat jump variation low impact tutorial",
    progressRule: "Monitor knee on landing. Any pain = remove the jump immediately and use the low-impact version. Progress height and depth when landings are consistently soft and controlled.",
    intensities: [{"l": "Easier", "d": "Squat hold only, no jump, 12 reps"}, {"l": "Current", "d": "Squat to jump, soft landing, 10 reps"}, {"l": "Harder", "d": "Deeper squat, higher jump"}, {"l": "Hardest", "d": "Add 3-second hold at bottom before jump"}],
  },
  'ex-pups2': {
    name: "Hollow Body Push-Up",
    exType: "conditioning",
    sets: "3",
    reps: "10",
    ring: false,
    coaching: "Ribs down, hips slightly tucked throughout. Full hollow body position the entire set. 3-second descent.",
    why: "Core + chest integrated. Hollow body position protects the lower back during the push.",
    search: "push up hollow body position tutorial",
    progressRule: "Stop when hollow body breaks down. Switch to incline rather than continue with poor form.",
    intensities: [{"l": "Easier", "d": "Incline, hollow body"}, {"l": "Current", "d": "Floor, hollow body, 3s eccentric"}, {"l": "Harder", "d": "12\u201315 reps"}, {"l": "Hardest", "d": "Ring push-up, hollow body"}],
  },
  'ex-hb3': {
    name: "Hollow Body Hold",
    exType: "rehab",
    sets: "3",
    reps: "30s",
    ring: false,
    coaching: "Slightly longer than Monday. Track your hold time every week \u2014 this is one of the most measurable improvements you'll make in Phase 1.",
    why: "Core brace signature. Gets longer every week. \u003cstrong\u003eBy week 6 you'll be at 40+ seconds consistently.\u003c/strong\u003e",
    search: "hollow body hold tutorial progression calisthenics",
    progressRule: "Slightly longer than Monday. By week 6, aim for 40+ seconds with flat back as your Phase 1 standard. Back off floor = set ends immediately.",
    intensities: [{"l": "Easier", "d": "Knees bent, arms by sides"}, {"l": "Current", "d": "Arms overhead, legs low, 30s"}, {"l": "Harder", "d": "40 seconds"}, {"l": "Hardest", "d": "50+ seconds, legs fully extended"}],
  },
  'ex-pig2': {
    name: "Pigeon Pose (modified)",
    exType: "mobility",
    sets: "1",
    reps: "60s/side",
    ring: false,
    coaching: "Front knee at 90\u00b0, support on hands or forearms. Sink into the hip. After Bulgarian split squats this is exactly what the hip flexor needs. Breathe into the tension \u2014 do not force depth.",
    why: "Hip flexor and glute release after unilateral leg strength work. Non-negotiable after the volume above.",
    search: "pigeon pose hip flexor glute stretch tutorial",
    progressRule: "Increase depth only when lower back stays flat for the full 60 seconds.",
    intensities: [],
  },
  'ex-cs': {
    name: "Couch Stretch",
    exType: "mobility",
    sets: "1",
    reps: "60s/side",
    ring: false,
    coaching: "Rear leg up against wall or box, front foot forward. Hip flexor of the rear leg is the target. This undoes the hip flexor tightening from Bulgarian split squats specifically.",
    why: "Hip flexor length. \u003cstrong\u003eTight hip flexors rotate the pelvis anteriorly\u003c/strong\u003e and directly cause the lower back compression you're working to eliminate.",
    search: "couch stretch hip flexor quad stretch tutorial",
    progressRule: "Work the stretch progressively \u2014 use a lower rear foot height if full position is too intense. Build over weeks.",
    intensities: [],
  },
  'ex-thu-fhc': {
    name: "Fire Hydrant Circles",
    exType: "mobility",
    sets: "1",
    reps: "10/side",
    ring: false,
    coaching: "On all fours. Full circles in both directions \u2014 bigger and slower than Tuesday. Let the hip joint move through its entire range. Thursday is about depth, not speed.",
    why: "Hip capsule mobility. \u003cstrong\u003eBigger circles on Thursday = more range accessed\u003c/strong\u003e after Wednesday's conditioning soreness.",
    search: "fire hydrant circles hip mobility warm up",
    progressRule: "Mobility never to pain. Focus on the full circle size \u2014 if any part of the circle feels restricted, slow down and breathe through that range.",
    intensities: [],
  },
  'ex-thu-cc': {
    name: "Cat Camel",
    exType: "mobility",
    sets: "1",
    reps: "14",
    ring: false,
    coaching: "Slower than Tuesday. Pause 2\u20133 seconds at each end. Try to feel individual vertebrae moving, not the whole spine at once. This is the difference between warming up and actually mobilizing.",
    why: "Spinal segmentation. \u003cstrong\u003eSlowing down reveals which levels are stiff\u003c/strong\u003e \u2014 that stiffness is exactly what Thursday is here to address.",
    search: "cat camel spinal mobility segmentation",
    progressRule: "Slower is always better. The goal is feeling each vertebra move \u2014 not achieving maximum range. Attention over effort.",
    intensities: [],
  },
  'ex-thu-pcp': {
    name: "Prying Cobra to Pike",
    exType: "mobility",
    sets: "1",
    reps: "5 slow cycles",
    ring: false,
    coaching: "5 full slow cycles. Hold the pike end position for 5 full breaths instead of Tuesday's 3. Let your hamstrings and hip flexors truly release \u2014 they won't on the first or second breath.",
    why: "Hip flexor + hamstring. \u003cstrong\u003eFive breaths at end range is where real tissue change happens\u003c/strong\u003e \u2014 Tuesday's 3 breaths warms it up, Thursday's 5 changes it.",
    search: "prying cobra to pike hip flexor stretch",
    progressRule: "Hold the pike position for 5 complete slow breaths. Progress to 6 breaths when 5 feels genuinely easy. Depth increases over months, not sessions.",
    intensities: [],
  },
  'ex-thu-cpp': {
    name: "Child Pose \u2014 Extended Hold",
    exType: "mobility",
    sets: "1",
    reps: "60s",
    ring: false,
    coaching: "Arms long overhead. Don't pulse \u2014 just stay. Breathe into your lower back. Let your hips sink toward your heels with each exhale. This is 60 full seconds, not 30.",
    why: "Lumbar decompression. \u003cstrong\u003e60-second hold creates genuine tissue release\u003c/strong\u003e that 30 seconds only begins. Thursday is where this matters most.",
    search: "child pose extended hold lower back release",
    progressRule: "Pure restoration \u2014 hold for the full 60 seconds. If you lose the breath connection, reset and refocus. This should feel progressively better across the hold, not worse.",
    intensities: [],
  },
  'ex-thu-tbr': {
    name: "Thoracic Bridge",
    exType: "mobility",
    sets: "1",
    reps: "8/side",
    ring: false,
    coaching: "2 extra reps per side vs Tuesday. Pause at end range and breathe. Feel the thoracic spine rotating, not just the shoulder. Progress depth by trying to stack your shoulders vertically over your hips.",
    why: "Thoracic rotation depth. \u003cstrong\u003e2 extra reps at slow tempo creates noticeably more mid-back opening\u003c/strong\u003e than Tuesday's activation version.",
    search: "thoracic bridge mobility lunge rotation",
    progressRule: "More time at end range beats more reps. If rotation is restricted, slow down and breathe. Fewer deep reps is always better than many shallow ones.",
    intensities: [],
  },
  'ex-thu-rsrdl': {
    name: "Romanian Split Stance Deadlift",
    exType: "mobility",
    sets: "1",
    reps: "12/side",
    ring: false,
    coaching: "12 reps per side, slower tempo. Pause at the bottom of the hinge for 2 seconds before returning. Feel the hamstring fully load at the bottom. Back stays flat \u2014 this is the whole exercise.",
    why: "Single-leg hamstring + posterior chain. \u003cstrong\u003ePause at the bottom on Thursday creates a loaded stretch\u003c/strong\u003e that Tuesday's movement version doesn't deliver.",
    search: "romanian split stance deadlift mobility hamstring",
    progressRule: "Progress to a lighter support touch when the hinge feels automatic. Back flat is the gate \u2014 any rounding means reduce the range.",
    intensities: [],
  },
  'ex-thu-gbale': {
    name: "Glute Bridge w/ Alt. Leg Extension",
    exType: "rehab",
    sets: "2",
    reps: "8/side",
    ring: false,
    coaching: "Hold the bridge longer at the top \u2014 2 seconds per rep. Hips stay level. This version is slower and more deliberate than Tuesday. Feel the glute working, not the hamstring.",
    why: "Hip stability maintenance. \u003cstrong\u003eThursday's slower tempo reveals any compensations\u003c/strong\u003e that speed was hiding on Tuesday.",
    search: "glute bridge alternating leg extension hip stability",
    progressRule: "Hips must stay perfectly level throughout. If any wobble or rotation appears, reduce the leg extension range. Add reps only when hip level is completely eliminated.",
    intensities: [],
  },
  'ex-thu-spuk': {
    name: "Scapula Push-Up (Kneeling)",
    exType: "rehab",
    sets: "2",
    reps: "10",
    ring: false,
    coaching: "Arms locked. Full range protraction and retraction. Slower than Tuesday \u2014 2 seconds each way. This is a maintenance set for shoulder health, not a strength set.",
    why: "Serratus anterior \u2014 shoulder blade control. \u003cstrong\u003eThursday keeps the motor pattern fresh\u003c/strong\u003e heading into Friday's ring volume.",
    search: "scapula push up serratus anterior kneeling",
    progressRule: "Full range every rep. Stop if range reduces. 10 reps here is maintenance quality work \u2014 never force through a reduced range.",
    intensities: [],
  },
  'ex-thu-syr': {
    name: "Scapula Y Raise",
    exType: "rehab",
    sets: "2",
    reps: "12",
    ring: false,
    coaching: "12 reps instead of Tuesday's 10. Slower, with a 2-second hold at the top. Shoulder stays away from your ear \u2014 if it creeps up, lower the range.",
    why: "Lower trapezius endurance. \u003cstrong\u003e12 slow reps on Thursday builds the postural endurance\u003c/strong\u003e that prepares you for Friday's pulling volume.",
    search: "scapula Y raise lower trapezius posture",
    progressRule: "Slower is always better. If upper traps take over, pause mid-rep. Progress when form is flawless for 2 full sessions.",
    intensities: [],
  },
  'ex-thu-qle': {
    name: "Quadruped Leg Extension",
    exType: "rehab",
    sets: "2",
    reps: "10/side",
    ring: false,
    coaching: "10 reps per side, 1-second pause at the top. Hips perfectly level throughout \u2014 no rotation allowed. Thursday's version adds the pause to increase the demand on glute med.",
    why: "Glute med stability \u2014 \u003cstrong\u003ethe pause version teaches the hip to hold, not just move.\u003c/strong\u003e Directly improves your single-leg balance and knee control.",
    search: "quadruped leg extension glute med activation",
    progressRule: "Hip level is the gate. If hips rotate even slightly, the set ends. Pause only works when hips are locked \u2014 a shaky pause doesn't count.",
    intensities: [],
  },
  'ex-thu-str': {
    name: "Scapula T Raise",
    exType: "rehab",
    sets: "2",
    reps: "12",
    ring: false,
    coaching: "12 reps, 2-second hold at top. Pairs with Y raise. Squeeze shoulder blades together at the top \u2014 feel the mid-back muscles engaging, not the upper traps.",
    why: "Mid-trapezius endurance. \u003cstrong\u003eTogether Y and T raises fix forward shoulder posture permanently\u003c/strong\u003e over a training year.",
    search: "scapula T raise mid trapezius posture",
    progressRule: "Same gate as Y raise. Lower traps, not upper. Add a 2-second pause once the movement feels solid. Progress intensity only when this feels genuinely easy for 2 weeks.",
    intensities: [],
  },
  'ex-thu-csq': {
    name: "Cossack Squat",
    exType: "mobility",
    sets: "2",
    reps: "6/side",
    ring: false,
    coaching: "6 reps per side instead of Tuesday's 5. Hold the bottom position for 3 breaths. Progress depth compared to Tuesday \u2014 try to go 5% lower if Tuesday's version felt stable.",
    why: "Hip + adductor mobility under load. \u003cstrong\u003eThursday's extra hold time is where real adductor length change occurs.\u003c/strong\u003e",
    search: "cossack squat hip mobility adductor stretch",
    progressRule: "Hold 3 full breaths at the bottom. If you can't breathe at the bottom position, reduce depth. Depth increases over months \u2014 patient consistent pressure.",
    intensities: [],
  },
  'ex-thu-trdl': {
    name: "Thoracic Rotation Deep Lunge",
    exType: "mobility",
    sets: "2",
    reps: "10",
    ring: false,
    coaching: "Sink deeper into the lunge than Tuesday. Hold the rotation at the top for 2 breaths. Feel each thoracic vertebra participating in the rotation. This movement hits your two injury areas simultaneously.",
    why: "\u003cstrong\u003eBest combined hip + thoracic movement you have.\u003c/strong\u003e Deeper lunge on Thursday = more hip flexor benefit at the same time.",
    search: "thoracic rotation deep lunge mobility",
    progressRule: "Focus on rotation depth. A few reps with full rotation is worth more than many shallow ones. Breathing into each rep is the technique.",
    intensities: [],
  },
  'ex-thu-fmr': {
    name: "Frog Mobility Rotation",
    exType: "mobility",
    sets: "2",
    reps: "12",
    ring: false,
    coaching: "12 reps, slower rocks, bigger rotation. Try to get slightly deeper than Tuesday. Any inner-groin pinching = back off immediately. This is months of patient work \u2014 Thursday gives you an extra dose.",
    why: "Inner groin + hip capsule. \u003cstrong\u003eThe extra 2 reps and slower tempo on Thursday is where cumulative hip mobility changes add up.\u003c/strong\u003e",
    search: "frog mobility rotation inner groin hip",
    progressRule: "Any inner-groin pinching = stop immediately. Progress is measured in months. Consistent gentle pressure beats aggressive attempts.",
    intensities: [],
  },
  'ex-thu-dh': {
    name: "Dead Hang",
    exType: "hold",
    sets: "2",
    reps: "35s",
    ring: false,
    coaching: "35 seconds \u2014 10 longer than Tuesday. Body completely relaxed. Shoulders rise naturally toward ears. Let your vertebrae separate. This is active recovery for your spine.",
    why: "Spinal decompression. \u003cstrong\u003eThursday's longer hang lets the discs rehydrate\u003c/strong\u003e after Wednesday's conditioning load. The most underrated recovery tool you have.",
    search: "dead hang spinal decompression shoulder mobility",
    progressRule: "Add 5 seconds per week. Goal is 60 seconds by end of Phase 1. Shoulders rise \u2014 don't pull them down. Grip failure is fine and normal.",
    intensities: [{"l": "Easier", "d": "25 seconds, drop if grip fails"}, {"l": "Current", "d": "35 seconds, body relaxed"}, {"l": "Harder", "d": "45 seconds"}, {"l": "Hardest", "d": "60 seconds"}],
  },
  'ex-thu-str2': {
    name: "Supine Thoracic Rotation",
    exType: "mobility",
    sets: "2",
    reps: "12/side",
    ring: false,
    coaching: "12 reps per side. Let the arm fall all the way to the floor on the other side \u2014 hold it there for 2 breaths. Don't rush back. This is the most accessible thoracic mobility drill you have and it costs nothing.",
    why: "Gentle thoracic mobility. \u003cstrong\u003ePost-conditioning soreness in the upper back responds especially well\u003c/strong\u003e to this movement. Zero spinal compression.",
    search: "supine thoracic rotation mobility",
    progressRule: "Let gravity open the chest. Rotation increases naturally over weeks. Breathing into the stretch is the technique \u2014 2 full slow breaths at end range.",
    intensities: [],
  },
  'ex-thu-tke': {
    name: "Slow Step-Down (VMO Focus)",
    exType: "rehab",
    sets: "2",
    reps: "10/side",
    ring: false,
    coaching: "4-second lower. Same as Tuesday but with slightly more attention \u2014 you're less fatigued than Tuesday so your form can be better. Feel the inner quad (VMO) catching the load on every rep.",
    why: "VMO retraining. \u003cstrong\u003eTwo sessions per week of this is the minimum effective dose\u003c/strong\u003e for MCL rehab \u2014 Tuesday activates it, Thursday reinforces it.",
    search: "slow step down eccentric VMO box",
    progressRule: "4-second lowering every rep. Thursday is a great day to try a slightly higher box than Tuesday and see how it feels. Progress only with perfect tracking.",
    intensities: [{"l": "Easier", "d": "Lower box, 3-second lower"}, {"l": "Current", "d": "Box step, 4-second lower, 10/side"}, {"l": "Harder", "d": "Higher box, 4-second lower"}, {"l": "Hardest", "d": "5-second lower, pause at bottom"}],
  },
  'ex-thu-lbw': {
    name: "Side-Lying Hip Abduction",
    exType: "rehab",
    sets: "2",
    reps: "15/side",
    ring: false,
    coaching: "15 reps per side on Thursday vs Tuesday's 15 \u2014 same reps, but add a 2-second pause at the top. That pause is what makes Thursday's version harder. Outer hip burn the whole way through.",
    why: "Glute medius \u2014 \u003cstrong\u003eThursday's pause version builds more endurance\u003c/strong\u003e in the stabilizer that protects your knee during every single-leg movement.",
    search: "side lying hip abduction glute medius bodyweight",
    progressRule: "2-second pause at top is the Thursday standard. If lower back activates, reduce range. Progress to a light dumbbell on the thigh when this feels easy across 2 sessions.",
    intensities: [{"l": "Easier", "d": "No pause, 12 reps"}, {"l": "Current", "d": "2-second pause, 15/side"}, {"l": "Harder", "d": "3-second pause, 15/side"}, {"l": "Hardest", "d": "Light dumbbell, 2-second pause"}],
  },
  'ex-thu-slbal': {
    name: "Single-Leg Balance Hold",
    exType: "rehab",
    sets: "2",
    reps: "40s/side",
    ring: false,
    coaching: "40 seconds vs Tuesday's 30. If Tuesday's eyes-open version felt stable, try eyes-closed here. Thursday is where proprioception work deepens \u2014 your system is familiar with the demand but not fatigued.",
    why: "Proprioceptive retraining. \u003cstrong\u003e40 seconds creates more neural adaptation than 30\u003c/strong\u003e \u2014 the nervous system needs to hold longer to build real stability.",
    search: "single leg balance proprioception eyes closed",
    progressRule: "Attempt eyes-closed on Thursday only after Tuesday's eyes-open version is completely stable for 30 seconds. Wobble is good. Falling = back to eyes-open version.",
    intensities: [{"l": "Easier", "d": "Eyes open, 30 seconds"}, {"l": "Current", "d": "Eyes open, 40 seconds"}, {"l": "Harder", "d": "Eyes closed, 30 seconds"}, {"l": "Hardest", "d": "Eyes closed, 40\u201350 seconds"}],
  },
  'ex-thu-9090': {
    name: "90-90 Hip Stretch",
    exType: "mobility",
    sets: "2",
    reps: "60s/side",
    ring: false,
    coaching: "60 seconds vs Tuesday's 45. Tall spine. Try to fold forward slightly in the last 15 seconds. This is the longest hip flexor hold in the program \u2014 the tissue change happens in this last quarter of the hold.",
    why: "Hip flexor + external rotation. \u003cstrong\u003e60-second holds create genuine tissue length change\u003c/strong\u003e that shorter holds only maintain. This is Thursday's most important hold.",
    search: "90 90 hip stretch hip flexor external rotation",
    progressRule: "Hold the full 60 seconds. Only try to fold forward if you can maintain a tall spine first. Progress depth in the last 15 seconds as a Thursday experiment.",
    intensities: [{"l": "Easier", "d": "Supported on hands, 45 seconds"}, {"l": "Current", "d": "Tall spine, 60 seconds"}, {"l": "Harder", "d": "Fold forward last 20 seconds"}, {"l": "Hardest", "d": "Full forward fold, 60+ seconds"}],
  },
  'ex-thu-sff': {
    name: "Standing Forward Fold",
    exType: "mobility",
    sets: "1",
    reps: "75s",
    ring: false,
    coaching: "75 seconds. Soft knees. Head completely heavy. Don't try to reach the floor \u2014 let gravity do all the work over the full hold. Breathe into the backs of your legs. Real hamstring length change happens here.",
    why: "Hamstring lengthening. \u003cstrong\u003eTight hamstrings pull the pelvis and compress the lower back.\u003c/strong\u003e 75 seconds of patient hanging is one of the most effective lower back investments in the program.",
    search: "standing forward fold hamstring gravity stretch",
    progressRule: "Never bounce. Let gravity work over the full 75 seconds. Touching the floor is an indicator of progress, not a goal to force. Add 5 seconds per week.",
    intensities: [],
  },
  'ex-thu-pig2': {
    name: "Pigeon Pose \u2014 Deep Hold",
    exType: "mobility",
    sets: "1",
    reps: "75s/side",
    ring: false,
    coaching: "75 seconds per side. Start on hands, then progress to forearms if comfortable. Breathe into the hip with each exhale. The real release happens after 45 seconds \u2014 that's why Thursday is 75.",
    why: "Deep hip flexor + glute release. \u003cstrong\u003eThe longest holds of the week create the most tissue adaptation.\u003c/strong\u003e This is the session where mobility actually changes.",
    search: "pigeon pose 60 seconds hip flexor adaptation",
    progressRule: "Progress from hands to forearms to forehead on floor \u2014 over months. Never force the hip down. Each exhale allows more depth. The release happens in the breath.",
    intensities: [],
  },
  'ex-thu-lhs': {
    name: "Lying Hamstring Stretch",
    exType: "mobility",
    sets: "1",
    reps: "60s/side",
    ring: false,
    coaching: "On your back, one leg raised, held with both hands or a towel. Other leg flat on floor. Back stays completely flat. 60 seconds \u2014 longer than any other hamstring hold in the program.",
    why: "Isolated hamstring with spine protected. \u003cstrong\u003eCloses the session with passive decompression\u003c/strong\u003e \u2014 no muscle activation, just gravity, gravity, gravity.",
    search: "lying hamstring stretch lower back decompression",
    progressRule: "Back flat the entire hold \u2014 if it lifts, reduce the leg angle. Only increase range when lower back stays flat for the full 60 seconds.",
    intensities: [],
  },
  'ex-rpush': {
    name: "Ring Push-Up",
    exType: "strength",
    sets: "3",
    reps: "8",
    ring: true,
    coaching: "Rings at mid-height. Don't let them flare. Slow the negative \u2014 3 seconds down. Harder than floor push-up because of the stabilizer demand.",
    why: "Horizontal push on rings. \u003cstrong\u003eBuilds chest + stabilizers missing from your Caliverse Monday routine.\u003c/strong\u003e",
    search: "ring push up tutorial progression stability",
    progressRule: "Stop 2 reps before failure \u2014 ring shoulder stress spikes sharply at failure. Never let rings flare outward. Progress when 3\u00d710 has 2\u20133 reps clearly in reserve across all sets.",
    intensities: [{"l": "Easier", "d": "Rings higher, easier angle"}, {"l": "Current", "d": "Mid-height, 8 reps, 3s negative"}, {"l": "Harder", "d": "Rings lower, 10 reps"}, {"l": "Hardest", "d": "Rings at floor level, full push-up"}],
  },
  'ex-rdip': {
    name: "Ring Dip (assisted)",
    exType: "strength",
    sets: "3",
    reps: "6",
    ring: true,
    coaching: "Box under feet for counterweight. Practice false grip. Lower to 90\u00b0, press up. Progress by reducing how much weight your feet bear on the box.",
    why: "Directly builds toward your \u003cstrong\u003ering dips goal.\u003c/strong\u003e The instability demands serious shoulder control that bar dips don't develop.",
    search: "ring dip assisted tutorial false grip",
    progressRule: "Reduce box assistance gradually when you feel in control through the full movement including the bottom transition. If bottom transition feels shaky, stay at current assistance level.",
    intensities: [{"l": "Easier", "d": "More weight on box, full support"}, {"l": "Current", "d": "Light foot support, 6 reps"}, {"l": "Harder", "d": "Toes only on box"}, {"l": "Hardest", "d": "Full ring dip, unassisted"}],
  },
  'ex-bpu': {
    name: "Ring-Assisted Pull-Up",
    exType: "strength",
    sets: "3",
    reps: "5",
    ring: true,
    coaching: "Hang from rings. One or both feet on a box behind you for assistance. Pull chin above rings every rep \u2014 full range is non-negotiable. Reduce foot contact each week. One foot, then toes only, then unassisted.",
    why: "Vertical pull with decreasing assistance. \u003cstrong\u003eWorking toward unassisted pull-up and eventually chest-to-bar.\u003c/strong\u003e Ring instability adds rotator cuff demand you won't get on a bar.",
    search: "ring assisted pull up foot support progression",
    progressRule: "Reduce foot contact weekly: both feet flat \u2192 one foot \u2192 toes \u2192 unassisted. Progress only when 3\u00d75 at current contact level has 2 reps clearly available. Never sacrifice full range for less assistance.",
    intensities: [{"l": "Easier", "d": "Both feet on box, more support"}, {"l": "Current", "d": "One foot touch-down, 5 reps"}, {"l": "Harder", "d": "Toes only on box"}, {"l": "Hardest", "d": "Full unassisted ring pull-up"}],
  },
  'ex-rfp': {
    name: "Ring Face Pull",
    exType: "strength",
    sets: "3",
    reps: "12",
    ring: true,
    coaching: "Rings at head height. Lean back, pull rings to forehead with hands finishing apart. External rotation at the top. Rear delt + rotator cuff.",
    why: "Shoulder health. \u003cstrong\u003eBalances all the pressing work.\u003c/strong\u003e Directly prevents ring-related shoulder injury over time.",
    search: "ring face pull rear delt rotator cuff tutorial",
    progressRule: "Gate: external rotation at top (hands finishing apart) must happen on every rep. No external rotation = reduce the load. Add reps before progressing intensity.",
    intensities: [{"l": "Easier", "d": "More upright body angle"}, {"l": "Current", "d": "45\u00b0 lean, 12 reps"}, {"l": "Harder", "d": "More horizontal, 12 reps"}, {"l": "Hardest", "d": "Near-horizontal, slow eccentric"}],
  },
  'ex-pyt': {
    name: "Prone Y + T Raise",
    exType: "rehab",
    sets: "3",
    reps: "10 each",
    ring: false,
    coaching: "Lie prone. Y raise (arms at 45\u00b0 overhead), then T raise (arms at 90\u00b0 to body). Thumbs up for both. Lift using lower and mid trap \u2014 not upper traps.",
    why: "Posture + pulling strength. Lower and mid trap. \u003cstrong\u003eThe weekly dose of trap work that fixes forward shoulder posture permanently.\u003c/strong\u003e",
    search: "prone Y T raise lower trap mid trap posture",
    progressRule: "Slow with a 2-second hold at the top. These are postural exercises \u2014 no momentum. Progress when lower traps feel clearly activated on every rep for 2+ sessions.",
    intensities: [{"l": "Easier", "d": "Floor, no weight, focus on form"}, {"l": "Current", "d": "Floor, 10 reps each, 2s hold"}, {"l": "Harder", "d": "Light plates or filled bottles"}, {"l": "Hardest", "d": "Heavier load, slower tempo"}],
  },
  'ex-rdl': {
    name: "Hip Hinge / RDL",
    exType: "strength",
    sets: "3",
    reps: "12",
    ring: false,
    coaching: "Stand, hinge at hip with soft knees, back flat. Feel hamstrings load. Return by driving hips forward. This is a hinge, not a squat \u2014 keep the spine neutral and the movement from the hip.",
    why: "Loads hamstrings and glutes instead of the spine. \u003cstrong\u003eThe most important movement pattern for long-term back health.\u003c/strong\u003e",
    search: "hip hinge RDL bodyweight tutorial lower back",
    progressRule: "Progress to a lighter support touch when the hinge feels completely automatic. Back flat is the gate \u2014 any rounding means reduce the range. Add load in Phase 2.",
    intensities: [{"l": "Easier", "d": "Hold wall for balance, small hinge"}, {"l": "Current", "d": "Ring hold, full hinge, 12 reps"}, {"l": "Harder", "d": "Light finger touch only"}, {"l": "Hardest", "d": "Unassisted, slow 3s lowering"}],
  },
  'ex-slgb2': {
    name: "Single-Leg Glute Bridge",
    exType: "strength",
    sets: "3",
    reps: "10/side",
    ring: false,
    coaching: "Drive through heel, squeeze glute at top for 2 seconds. Should feel this in the glute \u2014 if lower back or hamstring takes over, reposition foot closer to hips.",
    why: "Posterior chain. Same as Monday \u2014 \u003cstrong\u003eglute strength hits both knee and back protection\u003c/strong\u003e every week.",
    search: "single leg glute bridge form posterior chain",
    progressRule: "Same as Monday. 2-second glute squeeze at top. Feel the glute \u2014 if you feel hamstring or lower back instead, reposition. Progress to elevated version when 3\u00d710 has 3 reps left.",
    intensities: [{"l": "Easier", "d": "Both feet on floor, standard bridge"}, {"l": "Current", "d": "Single leg, 10 reps, 2s squeeze"}, {"l": "Harder", "d": "Foot elevated on box"}, {"l": "Hardest", "d": "Elevated + 3s hold at top"}],
  },
  'ex-db3': {
    name: "Dead Bug",
    exType: "rehab",
    sets: "3",
    reps: "8/side",
    ring: false,
    coaching: "Same strict standard as Monday. Back into floor the entire time. Slow and deliberate. If back lifts, reduce range before adding speed.",
    why: "Anti-extension core. \u003cstrong\u003eKeeps the lumbar from extending\u003c/strong\u003e \u2014 the exact motion that causes back flare-ups.",
    search: "dead bug exercise lower back anti-extension",
    progressRule: "Same strict standard as Monday. Back into floor the entire time. When this starts feeling genuinely easy, that means the anti-extension habit is building correctly.",
    intensities: [{"l": "Easier", "d": "One limb at a time, small range"}, {"l": "Current", "d": "Opposite arm/leg, 3s extend"}, {"l": "Harder", "d": "1-second hold at full extension"}, {"l": "Hardest", "d": "Resistance band between hands and knees"}],
  },
  'ex-sd': {
    name: "Step-Down (slow eccentric)",
    exType: "rehab",
    sets: "3",
    reps: "8/side",
    ring: false,
    coaching: "Stand on low step. Lower heel toward floor in 4 counts. Touch and return. Knee tracks over toes \u2014 no caving in. This is the VMO retraining exercise.",
    why: "Eccentric VMO + knee control. \u003cstrong\u003eRetrains the neuromuscular control\u003c/strong\u003e the MCL injury disrupted. 4-second lower = much more stimulus than fast reps.",
    search: "step down eccentric VMO knee control tutorial",
    progressRule: "4-second lowering every rep \u2014 count it out. Progress when 3\u00d78/side with perfect knee tracking (no caving) feels like 4 reps are left. Speed and grinding both defeat the purpose.",
    intensities: [{"l": "Easier", "d": "Smaller step, 3-second lower"}, {"l": "Current", "d": "Low step, 4-second lower, 8/side"}, {"l": "Harder", "d": "Higher step, 4-second lower"}, {"l": "Hardest", "d": "5-second lower, higher step"}],
  },
};
const PROGRAM = {
  monday: {
    eyebrow: "Monday \u00b7 Full Body Strength",
    title: "Push \u00b7 Pull \u00b7 Legs",
    warmup: "Fire hydrant circles \u00d78/side \u00b7 Cat camel \u00d710 \u00b7 Prying cobra to pike 30s \u00b7 Scapula Y raise \u00d710 \u00b7 Dead hang 20s",
    cooldown: "Chest opener \u00b7 lat doorway stretch \u00b7 child's pose \u00b7 pigeon modified \u00b7 supine thoracic rotation",
    blocks: [
      { title: "Vertical Pull", meta: "Caliverse \u00b7 3 rounds \u00b7 90s rest", danger: false, exercises: ["ex-arp", "ex-pun"] },
      { title: "Vertical + Horizontal Push", meta: "3 rounds \u00b7 90s rest", danger: false, exercises: ["ex-pbdip", "ex-scdip", "ex-pike"] },
      { title: "Lower Body", meta: "Caliverse \u00b7 3 rounds \u00b7 90s rest", danger: false, exercises: ["ex-sldl", "ex-wst", "ex-slgb"] },
      { title: "Core", meta: "Caliverse \u00b7 3 rounds \u00b7 60s rest", danger: false, exercises: ["ex-rsap", "ex-hkr"] },
      { title: "Horizontal Pull + Support", meta: "Caliverse \u00b7 3 rounds \u00b7 75s rest", danger: false, exercises: ["ex-rar", "ex-pbsh"] },
      { title: "Back + Knee Finish", meta: "Non-negotiable \u00b7 ~8 min", danger: false, exercises: ["ex-hb", "ex-db", "ex-tke", "ex-wsit"] },
    ],
  },
  tuesday: {
    eyebrow: "Tuesday \u00b7 Mobility + Prehab",
    title: "Flow \u00b7 Rebuild",
    warmup: "",
    cooldown: "",
    blocks: [
      { title: "Mobility Flow", meta: "Caliverse \u00b7 1 round \u00b7 60s rest", danger: false, exercises: ["ex-fhc", "ex-cc", "ex-pcp", "ex-cpp", "ex-tbr", "ex-rsrdl"] },
      { title: "Activation", meta: "Caliverse \u00b7 2 rounds \u00b7 60s rest", danger: false, exercises: ["ex-gbale", "ex-spuk", "ex-syr", "ex-qle", "ex-str", "ex-csq"] },
      { title: "Hips + Thoracic", meta: "Caliverse \u00b7 2 rounds \u00b7 60s rest", danger: false, exercises: ["ex-trdl", "ex-fmr", "ex-dh", "ex-str2"] },
      { title: "Knee Prehab", meta: "Added \u00b7 2 rounds \u00b7 60s rest", danger: false, exercises: ["ex-tke2", "ex-lbw", "ex-slbal", "ex-9090"] },
      { title: "Back + Shoulder Finisher", meta: "Added \u00b7 1 round", danger: false, exercises: ["ex-sup", "ex-dcs", "ex-pig"] },
    ],
  },
  wednesday: {
    eyebrow: "Wednesday \u00b7 Lower Body + Full Body",
    title: "Legs \u00b7 Power",
    warmup: "Hip circles \u00d710/side \u00b7 leg swings front/side \u00d710 \u00b7 bodyweight squat \u00d710 slow \u00b7 glute bridge \u00d715 \u00b7 dead hang 20s \u00b7 ankle circles",
    cooldown: "Cat camel \u00d710 \u00b7 child's pose 60s \u00b7 supine spinal twist 30s/side \u00b7 legs up wall 2 min",
    blocks: [
      { title: "Unilateral Leg Strength", meta: "3 rounds \u00b7 90s rest \u00b7 the hardest block", danger: false, exercises: ["ex-bss", "ex-noc", "ex-psq"] },
      { title: "Posterior Chain", meta: "3 rounds \u00b7 75s rest", danger: false, exercises: ["ex-ht", "ex-sldl2", "ex-cc"] },
      { title: "Full Body Circuit", meta: "3 rounds \u00b7 60s rest \u00b7 elevate heart rate", danger: false, exercises: ["ex-rrow2", "ex-sqjump", "ex-pups2"] },
      { title: "Recovery Finish", meta: "5 min \u00b7 always", danger: false, exercises: ["ex-hb3", "ex-pig2", "ex-cs"] },
    ],
  },
  thursday: {
    eyebrow: "Thursday \u00b7 Mobility + Deep",
    title: "Restore \u00b7 Strengthen",
    warmup: "",
    cooldown: "Supine thoracic rotation \u00b7 child's pose \u00b7 let everything settle",
    blocks: [
      { title: "Mobility Flow", meta: "1 round \u00b7 longer holds than Tuesday \u00b7 breathe into each rep", danger: false, exercises: ["ex-thu-fhc", "ex-thu-cc", "ex-thu-pcp", "ex-thu-cpp", "ex-thu-tbr", "ex-thu-rsrdl"] },
      { title: "Activation", meta: "2 rounds \u00b7 deliberate tempo \u00b7 feel each rep", danger: false, exercises: ["ex-thu-gbale", "ex-thu-spuk", "ex-thu-syr", "ex-thu-qle", "ex-thu-str", "ex-thu-csq"] },
      { title: "Hips + Thoracic \u2014 Deep Version", meta: "2 rounds \u00b7 longest holds of the week", danger: false, exercises: ["ex-thu-trdl", "ex-thu-fmr", "ex-thu-dh", "ex-thu-str2"] },
      { title: "Knee Prehab", meta: "2 rounds \u00b7 60s rest \u00b7 same importance as Tuesday", danger: false, exercises: ["ex-thu-tke", "ex-thu-lbw", "ex-thu-slbal", "ex-thu-9090"] },
      { title: "Deep Hamstring + Back Finisher", meta: "1 round \u00b7 close the session", danger: false, exercises: ["ex-thu-sff", "ex-thu-pig2", "ex-thu-lhs"] },
    ],
  },
  friday: {
    eyebrow: "Friday \u00b7 Rings Strength",
    title: "Skill \u00b7 Rings",
    warmup: "Cat camel \u00d78 \u00b7 fire hydrant circles \u00d76/side \u00b7 scapula Y raise \u00d710 \u00b7 dead hang 20s \u00b7 slow step-down \u00d75/side",
    cooldown: "Pec stretch \u00b7 lat doorway stretch \u00b7 child's pose \u00b7 pigeon pose \u00b7 supine thoracic rotation",
    blocks: [
      { title: "Push + Pull \u2014 Rings", meta: "3 rounds \u00b7 90s rest", danger: false, exercises: ["ex-rpush", "ex-rdip", "ex-bpu", "ex-rfp", "ex-pyt"] },
      { title: "Posterior Chain", meta: "3 rounds \u00b7 75s rest", danger: false, exercises: ["ex-rdl", "ex-slgb2"] },
      { title: "Back + Knee Finish", meta: "Same as Monday \u00b7 non-negotiable", danger: false, exercises: ["ex-hb3", "ex-db3", "ex-sd"] },
    ],
  },
};
